### ISSUE TITLE
Text clipping on blog page

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/digital-canada-ca#1268]
Hey Vic, I just noticed a few oddities on text / boxes sliding outside of expected scope.

I'm running of n-1 version of chrome, on macos. Seems to be fairly reproducible if you adjust the size of the browser window.

![image](https://user-images.githubusercontent.com/17616596/74541296-607b0480-4f0f-11ea-99bd-7a9d0102f202.png)

![image](https://user-images.githubusercontent.com/17616596/74541333-6e308a00-4f0f-11ea-8d7d-e61aa77b30ec.png)

**Comment by victoriachanimal** [comment]
Thanks for flagging @obrien-j ! Also see this in some FR posts (especially ones with more text) - I've added this to the list of website tasks and will get to it shortly.

**Comment by ftonato** [comment]
Hello,

I was looking at the code and realized that I can add a limit of lines that each block must have

On **_sections.scss** file we've these styles:

```scss
// https://github.com/cds-snc/digital-canada-ca/blob/fa984a9c83daf9d9ad05de7fb5a961d34afba15f/assets/sass/cds/_sections.scss#L1014
h2 {
  margin-top: 0;
  font-size: 24px;

  @include tablet { // This rule will limit the number of lines to 4
    overflow: hidden;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 4;
    -webkit-box-orient: vertical;
  }
}

// https://github.com/cds-snc/digital-canada-ca/blob/fa984a9c83daf9d9ad05de7fb5a961d34afba15f/assets/sass/cds/_sections.scss#L1027
.author {
  font-size: 18.5px;

  @include tablet { // This rule will limit the number of lines to 4
    overflow: hidden;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 4;
    -webkit-box-orient: vertical;
  }
}

// https://github.com/cds-snc/digital-canada-ca/blob/fa984a9c83daf9d9ad05de7fb5a961d34afba15f/assets/sass/cds/_sections.scss#L1031
.summary {
  color: $icon-grey;
  font-size: 18.5px;

  @include tablet { // This rule will limit the number of lines to 10
    overflow: hidden;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 10;
    -webkit-box-orient: vertical;
  }
}
```
We can use the same rules for `mobile`, `tablet` and `desktop` changing the **line-clamp** number...

Before             |  After
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/5417662/75342236-ea22be80-588d-11ea-8224-7db3dc6f879b.png)  |  ![image](https://user-images.githubusercontent.com/5417662/75342138-bb0c4d00-588d-11ea-82f4-bc214e14b561.png)

/cc @victoriachanimal
